---

- name: Get timestamp
  local_action: shell date +%s%3N
  register: timestamp
  run_once: True
  become: False

- name: Create release archive
  local_action: >
      command chdir=../{{ django_project_name }}
      zip --filesync -R ../ansible/{{ django_project_name }}.zip '*'
        -x 'db.sqlite3'
        -x '*/.env.local'
        -x 'media/*'
        -x '*__pycache__*'
        -x '*.swp'
        -x 'node_modules/*'
  become: False

- name: Ensure /var/www and /var/media exist
  file: path={{ item }} owner=www-data group=www-data mode=0775 state=directory
  with_items:
    - /var/www
    - /var/media

- include: install.yaml
  become_user: www-data

- name: Run django-admin mediabackup every day
  cron:
    name: back up media files
    minute: 30
    hour: 3
    job: cd /var/www/{{ domain }}/current && ./venv/bin/python manage.py mediabackup >/dev/null 2>&1
    state: present
  become: False

- name: Run django-admin dbbackup every hour
  cron:
    name: back up the database
    minute: 5
    job: cd /var/www/{{ domain }}/current && ./venv/bin/python manage.py dbbackup >/dev/null 2>&1
    state: present
  become: False

- name: Run django-admin publish_scheduled_pages every hour
  cron:
    name: publish scheduled pages in Wagtail
    minute: 0
    job: cd /var/www/{{ domain }}/current && ./venv/bin/python manage.py publish_scheduled_pages
    state: present
  become: False

- name: Update app version
  file:
    state: link
    src: "{{ release_dir }}"
    path: /var/www/{{ domain }}/current
  notify:
    - test and reload Nginx
    - restart uWSGI

# TODO clean up old deploys
